### ISSUE TITLE
Boot hub On premise 

### ISSUE THREAD

**Issue by jvmlet** [boothub-org/boothub#1]
Hi
Congrats with first issue 😀 :
Is it possible to host boothub locally and how to publish templates to be hosted by web app?

**Comment by siordache** [comment]
Yes, it s possible. In the next days I will update the documentation with detailed informatiom about this topic.
Until then, here is a short howto:

### EDIT: obsolete - see next comment

- create a new GitHub [OAuth application](https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/) with *Application name*: `BootHub` and *Authorization callback URL*: `http://localhost:8080/callback`.
- in the `boothub-web/src/main/resources` directory create a file named `boothub-oauth.cfg`. Use [boothub-oauth.template.cfg](https://github.com/boothub-org/boothub/blob/master/boothub-web/src/main/resources/boothub-oauth.template.cfg) as template. Set *callbackUrl* to: `http://localhost:8080/callback`, *key* to the *Client ID* value of your OAuth applcation, and *secret* to the *Client Secret* value.
- create a postgres database and set the value of the environment variable `DATABASE_URL` to its corresponding URL (`postgres://...`)
- execute `gradlew build`
- unzip `boothub-web/build/distributions/boothub-web-1.0.1-SNAPSHOT.zip` and run `boothub-web` in the `bin` directory.

To publish a template go to the `Template Manager` tab of the web application and enter the URL of the zip file containing your template.  Example:
https://github.com/boothub-org/boothub-template-java-groovy/releases/download/v1.0.0/java-groovy-1.0.0.zip

**Comment by siordache** [comment]
I just released version 1.1.0, which offers better support for installing BootHub on-premises.
See the [documentation](http://doc.boothub.org/releases/latest/#on_premises) for details.

**Comment by jvmlet** [comment]
Thanks @siordache
